Repository Raptacon/Robot-2022, pull requests merged in 2022-01, with the labels that each got.

#21 New bot config
  configs/newBot.yml
Labels: enhancement

#19 Better color sensor
  components/colorSensor.py
Labels: enhancement

#20 Go to dist rewrite
  components/driveTrainGoToDist.py
Labels: refactor

#25 Added docs to shooter system.
  components/hopperMotor.py
  components/intakeMotor.py
  components/shooterMotors.py
Labels: documentation
